---

- hosts: all
  become: true
  tasks:
        
  - name: update repository index
    dnf:
      update_cache: yes

  - name: install apache2 package
    dnf:
      name: httpd
      state: absent
        
  - name: add php support for apache
    dnf:
      name: 
          - php
          - php-cli
          - php-common
          - php-mysqlnd
          - php-fpm
          - php-devel
      state: absent

