---
- hosts: all
  become: true
  tasks:
    - name: Update all packages on all servers
      tags: always
      dnf:
        name: "*"
        state: latest
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "AlmaLinux" or ansible_distribution_version == "9.5"

- hosts: web_servers
  become: true
  tasks:
    - name: Install Apache2 and PHP packages (only on web_servers)
      tags:
        - apache 
        -  httpd
        -  almalinux
      dnf:
        name:
          - httpd
          - php
        state: latest
        update_cache: yes
      when: ansible_distribution_version == "9.5"
    
    - name: copy default html file for site
      tags: 
        - apache
        - apache2
        - httpd
      copy:
        src: files/default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644


- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb client and server (Almalinux)
    tags:
      - almalinux
      - db
      - mariadb 
    dnf:
      name:
        - mariadb
        - mariadb-server  
      state: latest
    when: ansible_distribution == "AlmaLinux"

  - name: Enable and start MariaDb service
    tags: samba
    systemd:
      name: mariadb
      enabled: yes
      state: started


- hosts: file_servers
  become: true
  tasks:
  
  - name: install samba package
    package: 
      name: samba
      state: latest

