- name: install mariadb server package (AlmaLinux)
  tags: 
    - almalinux
    - db
    - mariadb
    - mariadb-server
  dnf:
    name: mariadb
    state: latest
  when: ansible_distribution == "AlmaLinux"

